#! /bin/bash

#
# Andri Pétur Þrastarson
#
# A script that slices audio files. 
# - now with three arguments! ! !

if [ $# -lt 3 ]; then
  echo "$0: How to use:"
  echo "Insert file path, how many clips you want, and the file extension"
exit
else
  echo "The Chosen File: $1"
  echo "Will be cut into: $2 pieces."
fi

# Make al dem variables
EXTENSION=$3
FILEPATH=$1
FILENAME=`basename "${FILEPATH}" ${EXTENSION}` 
SAMPLES=`soxi -s "${FILEPATH}"`
WAAR=`dirname "${FILEPATH}"`
CLIPSIZE=`expr ${SAMPLES} / $2`

# Trim and create files.
for (( i=0 ; i <= $2-1; i++))
do
let x=$i*${CLIPSIZE}
let y=$i+1
let x2=$y*${CLIPSIZE}

sox "${FILEPATH}" "${FILENAME}.${i}clip.wav" trim =${x}s =${x2}s
mv "${FILENAME}.${i}clip.wav" "$WAAR"

echo "${FILENAME}.${i}clip.wav is gemaakt."
       
done

